### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by MMJM** [goldmansachs/reladomo-kata#25]
Hi,

I'm going through the Code Kata which by the way is a great way to learn. I'm having an issue with one of the exercises.

In ExercisesAdvancedFinder testQ5a and testQ5b

```
//-------------- Question 5 ------------------------------------------------------
// Find the average age of all Person objects.  This is a two stage question:
// 1) Find the average without using any special Mithra features.
// 2) Find the average using Mithra's AggregateList feature.

    public double getAverageAgeNormalMithra()
    {
        return  new PersonList(PersonFinder.all()).stream().mapToInt(p -> p.getAge()).average().getAsDouble();
    }

    @Test
    public void testQ5a()
    {
        Assert.assertEquals(34.75, this.getAverageAgeNormalMithra(), 0.0);
    }

    public double getAverageAgeUsingAggregateList()
    {
        AggregateList agg = new AggregateList(PersonFinder.all());
        agg.addAggregateAttribute("avgAge", PersonFinder.age().avg());
        return agg.get(0).getAttributeAsDouble("avgAge");
    }

    @Test
    public void testQ5b()
    {
        Assert.assertEquals(34.75, this.getAverageAgeUsingAggregateList(), 0.0);
        final Person person = new Person();
        person.setName("Michael Caine");
        person.setCountry("USA");
        person.setAge(65);
        person.insert();
        Assert.assertEquals(this.getAverageAgeNormalMithra(), this.getAverageAgeUsingAggregateList(), 0.0);
    }
```

The above is my answers to the questions. testQ5a produces a pass but testQ5b produces a fail.

I can't for the life of me see how to get testQ5b to work. The data type of the Person.age column is an int and the avg function in H2 would produce an int result from what I read of H2 (I'm new to H2). So it would appear that the getAttributeAsDouble will not affect the answer returned from H2. I get 34 returned and not the 34.75 answer which is what I got in testQ5a.

Can you tell me how this should work?

My only suggestion on the Kata is that it would be great to have the solutions to check against.

Reladomo is looking great as I progress through its features. Thanks for the work.

**Comment by gs-rezaem** [comment]
Sorry about that... it's a bit of a trick question, more suitable when this Kata is done in a classroom setting. 

You essentially have to figure out a way to cast from int to double on the database side. It's not really H2 specific; the same thing happens with all databases.

So this is the trick: use a bit of math to force a double:
```PersonFinder().age().times(1.0).avg()```

Hope that helps.

P.S. Wouldn't it be nice if there was a simpler castToDouble() method on IntegerAttribute? 💡 for contribution?

**Comment by MMJM** [comment]
@gs-rezaem 

Ah I see thanks for the tip there.

I'd love to make use of reladomo in my project Just a little question. 

Is reladomo alive and kicking? 

I assume it is as you use it internally in a number of projects and the quick response above makes me think it is.

I would love to contribute and offer ideas where I can.

**Comment by gs-rezaem** [comment]
Very much alive and kicking 😄

**Comment by MMJM** [comment]
@gs-rezaem 

Fantastic :)
