### ISSUE TITLE
Odd results in Audit Exercises

### ISSUE THREAD

**Issue by Zynde** [goldmansachs/reladomo-kata#26]
Hi,

I'm getting what looks like an odd result from the Audit exercises. 

My code for the exercise is here.

![image](https://user-images.githubusercontent.com/31379998/33740996-757a1524-dbee-11e7-857e-566afc5e740d.png)

The test data hasn't been modified and looks like this.

![image](https://user-images.githubusercontent.com/31379998/33741021-87a971cc-dbee-11e7-8ed9-9907dddf326b.png)

This is what is in the debug output. It shows both the "Build Bridge" "Restarted" entry and the "Dam River" "Damming" entry as having ProcessingDateFrom times of 05:00:00.000 which is an hour behind the 06:00:00.000 they should be. The other entries have not been adjusted in any way so I can't see any reason these two entries have been adjusted.

![image](https://user-images.githubusercontent.com/31379998/33740979-5e0589f0-dbee-11e7-9cf9-bca206410e35.png)

I am in Australia/Brisbane with no daylight savings so I am standard AEST time.

Because of this time difference my test is failing. I don't think I have done anything wrong.

Any ideas?

**Comment by gs-rezaem** [comment]
Thanks for reporting this issue. We'll have to either amend the docs to force America/New_York as the timezone (```-Duser.timezone=America/New_York```) on the command line, or fix the processing date to do UTC conversions (```timezoneConversion="convert-to-utc"```) and change the data.

**Comment by Zynde** [comment]
Any reason why some of them were changing?

Is it much work to UTC the ProcessingDate?

**Comment by gs-rezaem** [comment]
UTC should be straight forward. @nikhilnanivadekar will try to do the utc thing over the next day or two.

**Comment by Zynde** [comment]
Oh cool.

**Comment by Zynde** [comment]
I've just had a thought.

I wonder if the TimeZone.inDaylightTime has the knowledge of historic daylight savings. Here in Queensland we no longer have Daylight Savings. However we did have and it would not always have been as it is a more recent idea.

The Times back in the 1960's are coming through fine. The times in the 2000's are fine it is the dates in the 1990's that are 1 hour adjusted which when I was a kid did have daylight savings. 

I shall look at when Daylight Savings here in Queensland Australia come in to effect and ended to see if that matches up.

**Comment by nikhilnanivadekar** [comment]
I tried UTC but the tests break in various timezones. So, the fix I have in #27 is to set the database timezone to be same as local timezone, and convert the processing, business dates to database timezone.

**Comment by Zynde** [comment]
If you look at this it details the Daylight Savings years here in Queensland, Australia.

https://en.m.wikipedia.org/wiki/Daylight_saving_time_in_Australia

I tried a date in 1972 and got the same 1 hour adjustment of the time. So the TimeZone.inDaylightTime is pretty smart. 

So I guess the problem for me is that the assert in the test is looking for a specific date and time and not one that has been adjusted.

**Comment by Zynde** [comment]
OR maybe it is more that if I am inserting the following Daylight Savings or not 
1      , "Build Bridge" , "Restarted", "1990-01-01 06:00:00.0", "1992-12-01 23:59:00.0"
I should get the same back and not
1      , "Build Bridge" , "Restarted", "1990-01-01 05:00:00.0", "1992-12-01 23:59:00.0"

**Comment by gs-rezaem** [comment]
I tried switching using Reladomo's built in timezone conversion to UTC, and it works with almost every timezone and date, except Australia/Brisbane and 1990-01-01 06:00:00.0. I even started using Joda time's parsing to see if that made a difference, but it didn't.

As far as the kata is concerned, it's just a learning tool and I'm pretty sure you've learned more than was intended :smile:

I'm not certain if there is a core issue here that needs to be addressed. If you run into a problem in your own code, let us know.

**Comment by Zynde** [comment]
@gs-rezaem Lucky me for living near Brisbane....
Thanks for looking in to it. I'll move on with more integration with my main app and see how I go.
